config/routes.rb
Rails.application.routes.draw do
  resources :spell_lists
  resources :spells
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spell.rb
class Spell < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :level, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9}
  validates :range, presence: true
  validates :school, presence: true
  validates :casting_time, presence: true
  validates :duration, presence: true
  validates :description_short, presence: true
  validates :description_long, presence: true

  has_and_belongs_to_many :spell_lists

  def to_label
    "#{name} | #{level} | #{description_short}"
  end

  scope :by_level_and_name, -> { order(:level, :name) }
  scope :level, ->(level_number) { where(level: level_number) }
end

app/models/spell_list.rb
class SpellList < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_and_belongs_to_many :spells
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spell_lists_controller.rb
class SpellListsController < ApplicationController
  # GET /spell_lists
  # GET /spell_lists.json
  def index
    @spell_lists = SpellList.all
  end

  # GET /spell_lists/1
  # GET /spell_lists/1.json
  def show
    @spell_list = SpellList.find(params[:id])
  end

  # GET /spell_lists/new
  def new
    @spell_list = SpellList.new
    @spells = Spell.all
  end

  # GET /spell_lists/1/edit
  def edit
    @spell_list = SpellList.find(params[:id])
    @spells = Spell.all
  end

  # POST /spell_lists
  # POST /spell_lists.json
  def create
    @spell_list = SpellList.new(spell_list_params)
    @spells = Spell.all

    if @spell_list.save
      redirect_to @spell_list, notice: 'Spell List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spell_lists/1
  # PATCH/PUT /spell_lists/1.json
  def update
    @spell_list = SpellList.find(params[:id])
    @spells = Spell.all
    if @spell_list.update(spell_list_params)
      redirect_to @spell_list, notice: 'Spell List was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spell_lists/1
  # DELETE /spell_lists/1.json
  def destroy
    @spell_list = SpellList.find(params[:id])
    @spell_list.destroy
    redirect_to spell_lists_url, notice: 'Spell List was successfully destroyed.'
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_list_params
      params.require(:spell_list).permit(:title, spell_ids: [])
    end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  # GET /spells
  # GET /spells.json
  def index
    @spells = Spell.all
  end

  # GET /spells/1
  # GET /spells/1.json
  def show
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/1/edit
  def edit
  end

  # POST /spells
  # POST /spells.json
  def create
    @spell = Spell.new(spell_params)

    if @spell.save
      redirect_to @spell, notice: 'Spell was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /spells/1
  # PATCH/PUT /spells/1.json
  def update
    if @spell.update(spell_params)
      redirect_to @spell, notice: 'Spell was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /spells/1
  # DELETE /spells/1.json
  def destroy
    @spell.destroy
    redirect_to spells_url, notice: 'Spell was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_params
      params.require(:spell).permit(:name, :level, :range, :school, :casting_time, :duration, :description_short, :description_long)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spell_lists_helper.rb
module SpellListsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Spellbook

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/spell_lists/_form.haml
= simple_form_for @spell_list do |f|
  = f.input :title
  - for level_number in 0..9 do
    %strong Level #{a}
    = f.association :spells, as: :check_boxes, label: false, collection: Spell.by_level_and_name.level(level_number)
  = f.button :submit

app/views/spell_lists/edit.haml
%h1 Editing Spell List
= render 'form', spell_list: @spell_list
= link_to 'Show', @spell_list
|
= link_to 'Back', spell_lists_path

app/views/spell_lists/index.haml
%p#notice= notice
%h1 Spell lists
%table
  %thead
    %tr
      %th Title
      %th{colspan: "3"}
  %tbody
    - @spell_lists.each do |spell_list|
      %tr
        %td= spell_list.title
        %td= link_to 'Show', spell_list
        %td= link_to 'Edit', edit_spell_list_path(spell_list)
        %td= link_to 'Destroy', spell_list, method: :delete, data: { confirm: 'Are you sure?' }

%br/
= link_to 'New Spell List', new_spell_list_path

app/views/spell_lists/new.haml
%h1 New Spell List
= render 'form', spell_list: @spell_list
= link_to 'Back', spell_lists_path

app/views/spell_lists/show.haml
%p#notice= notice
%p
  %strong Title:
  = @spell_list.title
  %br
  %strong Spells:
  %ul
    - @spell_list.spells.by_level_and_name.each do |spell|
      %li
        = link_to "#{spell.name}", spell_path(spell)
        |
        = spell.level
        |
        = spell.school
        |
        = spell.description_short

= link_to 'Edit', edit_spell_list_path(@spell_list)
|
= link_to 'Back', spell_lists_path

app/views/spells/_form.haml
= form_with(model: spell, local: true) do |form|
  - if spell.errors.any?
    #error_explanation
      %h2
        = pluralize(spell.errors.count, "error")
        prohibited this spell from being saved:
      %ul
        - spell.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :level
    = form.number_field :level
  .field
    = form.label :range
    = form.text_field :range
  .field
    = form.label :school
    = form.text_field :school
  .field
    = form.label :casting_time
    = form.text_field :casting_time
  .field
    = form.label :duration
    = form.text_field :duration
  .field
    = form.label :description_short
    = form.text_field :description_short
  .field
    = form.label :description_long
    = form.text_area :description_long
  .actions
    = form.submit

app/views/spells/edit.haml
%h1 Editing Spell
= render 'form', spell: @spell
= link_to 'Show', @spell
|
= link_to 'Back', spells_path

app/views/spells/index.haml
%p#notice= notice
%h1 Spells
%table
  %thead
    %tr
      %th Name
      %th Level
      %th Range
      %th School
      %th Casting time
      %th Duration
      %th Description short
      %th Description long
      %th{colspan: "3"}
  %tbody
    - @spells.by_level_and_name.each do |spell|
      %tr
        %td= spell.name
        %td= spell.level
        %td= spell.range
        %td= spell.school
        %td= spell.casting_time
        %td= spell.duration
        %td= spell.description_short
        %td= spell.description_long
        %td= link_to 'Show', spell
        %td= link_to 'Edit', edit_spell_path(spell)
        %td= link_to 'Destroy', spell, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Spell', new_spell_path

app/views/spells/new.haml
%h1 New Spell
= render 'form', spell: @spell
= link_to 'Back', spells_path

app/views/spells/show.haml
%p#notice= notice
%p
  %strong Name:
  = @spell.name
%p
  %strong Level:
  = @spell.level
%p
  %strong Range:
  = @spell.range
%p
  %strong School:
  = @spell.school
%p
  %strong Casting time:
  = @spell.casting_time
%p
  %strong Duration:
  = @spell.duration
%p
  %strong Description short:
  = @spell.description_short
%p
  %strong Description long:
  = @spell.description_long
= link_to 'Edit', edit_spell_path(@spell)
|
= link_to 'Back', :back